# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rspec-core/all/rspec-core.rbi
#
# rspec-core-3.5.4
module RSpec::Support
  def self.require_rspec_core(f); end
end
module RSpec
  def self.clear_examples; end
  def self.configuration; end
  def self.configuration=(arg0); end
  def self.configure; end
  def self.const_missing(name); end
  def self.current_example; end
  def self.current_example=(example); end
  def self.reset; end
  def self.world; end
  def self.world=(arg0); end
  extend RSpec::Core::Warnings
end
module RSpec::Core
  def self.path_to_executable; end
end
class RSpec::Core::Time
  def self.now; end
end
class Module
  def context(*a, &b); end
  def describe(*a, &b); end
  def example_group(*a, &b); end
  def fcontext(*a, &b); end
  def fdescribe(*a, &b); end
  def shared_context(name, *args, &block); end
  def shared_examples(name, *args, &block); end
  def shared_examples_for(name, *args, &block); end
  def xcontext(*a, &b); end
  def xdescribe(*a, &b); end
end
